name: Building pyGHDL (Python Bindings for libghdl)

on:
  workflow_call:

jobs:
  Checks:
    name: 'ğŸ Checking Python bindings'
    runs-on: ubuntu-latest

    steps:
      - name: 'ğŸ§° Checkout'
        uses: actions/checkout@v4

      - name: 'ğŸ Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 'ğŸ”§ Install dependencies'
        run: |
          sudo apt update -qq
          sudo apt install -y --no-install-recommends gnat
          python -m pip install --disable-pip-version-check black wheel

      - name: 'ğŸš§ Update Python bindings'
        run: ./scripts/update_py_bindings.sh

      - name: 'ğŸš¦ Check if Python bindings changed'
        run: |
          git diff --stat
          echo "NOTE: Bindings can be updated by executing ./scripts/update_py_bindings.sh (see previous step)"
          git diff --exit-code

      - name: 'ğŸš¦ Check if python follows code formatting standards'
        run: python -m black --check pyGHDL

  Package:
    name: 'ğŸ Package pyGHDL'
    runs-on: ubuntu-latest
    needs:
      - Checks

    steps:
      - name: 'ğŸ§° Checkout'
        uses: actions/checkout@v4

      - name: 'ğŸ Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 'ğŸ”§ Install dependencies'
        run: |
          python -m pip install --disable-pip-version-check "pyTooling[packaging]<5.0" wheel

      - name: ğŸ”¨ Build Python package (source distribution)
        run: python setup.py sdist

      - name: ğŸ”¨ Build Python package (binary distribution - wheel)
        run: python setup.py bdist_wheel

      - name: 'ğŸ“¤ Upload artifact: pyGHDL'
        uses: actions/upload-artifact@v4
        with:
          name: pyGHDL
          path: dist/
          if-no-files-found: error
